title: Dovry's totally alright tech blog
#email:
description: >-
  A collection of my thoughts, troubleshooting documentation, tips'n'trick, and (not so) useful code snippets
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.dovry.cloud"
# twitter_username:
github_username:  dovry

timezone: Europe/Oslo
future: true
#theme: jekyll-theme-merlot
remote_theme: yizeng/jekyll-theme-simple-texture
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
