title: Dovry's totally alright blog
description: >-
  A collection of my thoughts, troubleshooting documentation, tips'n'trick, and (not so) useful code snippets
# baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://blog.dovry.cloud"
url: "https://dovry.github.io"
github_username:  dovry

timezone: Europe/Oslo
future: true

#remote_theme: "mmistakes/jekyll-theme-basically-basic"

logo_img: /assets/tux-logo.png

plugins:
  - jekyll-feed

include: ['_pages', '_layouts']

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
